# Generated by Django 4.2.3 on 2023-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importado', models.BooleanField(default=False)),
                ('numero_serie', models.CharField(max_length=15, verbose_name='SERIE')),
                ('produto', models.CharField(max_length=100, unique=True)),
                ('tombo', models.DecimalField(decimal_places=0, max_digits=5)),
                ('responsavel', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponivel'), ('Alocado', 'Alocado'), ('Quebrado', 'Quebrado'), ('Manutenção', 'Manutenção')], max_length=10)),
            ],
            options={
                'ordering': ('produto',),
            },
        ),
    ]
