# Generated by Django 4.2.3 on 2023-07-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tombo',
        ),
        migrations.AddField(
            model_name='produto',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque atual'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque mínimo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(default=0, max_length=8, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='preço'),
        ),
    ]
